name: Create pr

on:
  workflow_dispatch:

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
      - uses: ./actions/staging-tests
        with:
          token: ${{ steps.app-token.outputs.token }}
          
      - name: Checkout repository
        with:
          token: ${{ steps.app-token.outputs.token }}
          ref: ${{ github.head_ref }}
          # Make sure the value of GITHUB_TOKEN will not be persisted in repo's config
          persist-credentials: false

      - name: Create changes and new branch
        run: |
          # Configure git
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          # Create and switch to a new branch called "new-feature"
          git checkout -b new-feature
          # Make some changes (e.g., create a new file)
          echo "This is an automatically generated file." > newfile.txt
          # Stage and commit changes
          git add newfile.txt
          git commit -m "Add newfile.txt with automated content" || echo "No changes to commit"

      - name: Push new branch to origin
        run: git push origin new-feature

      - name: Create a pull request
        uses: actions/github-script@v6
        with:
          github-token: ${{ steps.app-token.outputs.token }}
          script: |
            const { data: pullRequest } = await github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `new pr into beta`,
              head: `new-feature`,
              base: 'beta',
              body: `asd.`
            });
            console.log(`Created pull request: ${pullRequest.html_url}`);
