name: Auto Create PR

on:
  push:
    branches:
      - master

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create PR from master to develop
        run: |
          gh pr create --base develop --head new-feature --title "Auto Merge asd to Develop" --body "Automated PR"
