name: Release on master
on:
  push:
    branches:
      - master

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Get version
        id: get_version
        run: |
          MARKETING_VERSION="1.90"
          BUILD_NUMBER="333"
          
          echo "Current Marketing Version: $MARKETING_VERSION"
          echo "Current Build Number: $BUILD_NUMBER"
          TAG_NAME="v${MARKETING_VERSION}b${BUILD_NUMBER}"
          echo $TAG_NAME
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV

      - name: Install GitHub CLI
        run: sudo apt-get install gh

      - name: Authenticate with GitHub CLI
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Create a pull request
        uses: actions/github-script@v6
        with:
          script: |
            const { data: pullRequest } = await github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `Merge master into develop after release`,
              head: `master`,
              base: 'develop',
              body: `This PR merges master into develop after a release.`
            });
            const fs = require('fs');
            fs.appendFileSync(envFile, `PR_URL=${pullRequest.html_url}\n`);
            console.log(`Created pull request: ${pullRequest.html_url}`);

      - name: Get latest commit SHA of PR
        id: get-sha
        run: |
          PR_NUMBER=$(gh pr view $PR_URL --json number -q .number)
          COMMIT_SHA=$(gh pr view $PR_NUMBER --json headRefOid -q .headRefOid)
          echo "COMMIT_SHA=$COMMIT_SHA" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Trigger unit tests on PR commit
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/unit-tests.yml/dispatches \
            -d '{"ref":"${{ env.COMMIT_SHA }}"}'
