name: Release on master
on:
  push:
    branches:
      - master

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Get version
        id: get_version
        run: |
          MARKETING_VERSION="1.90"
          BUILD_NUMBER="333"
          
          echo "Current Marketing Version: $MARKETING_VERSION"
          echo "Current Build Number: $BUILD_NUMBER"
          TAG_NAME="v${MARKETING_VERSION}b${BUILD_NUMBER}"
          echo $TAG_NAME
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV

      - name: Install GitHub CLI
        run: sudo apt-get install gh

      - name: Authenticate with GitHub CLI
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Create a pull request
        uses: actions/github-script@v6
        with:
          script: |
            const { data: pullRequest } = await github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `Merge master into develop after release`,
              head: `master`,
              base: 'develop',
              body: `This PR merges master into develop after a release.`
            });
            console.log(`Created pull request: ${pullRequest.html_url}`);
