name: Auto Review on PR

on:
  pull_request:
    types: [opened]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Request changes on PR
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = context.payload.pull_request;
            const sourceBranch = pr.head.ref;
            let message = "";
            if (sourceBranch === "master" || sourceBranch === "beta") {
              message = "please use merge commit";
            } else if (sourceBranch.startsWith("issues/") || sourceBranch.startsWith("feature/")) {
              message = "please squash";
            } else {
              message = "please be mindful when chosing merge method";
            }
            await github.rest.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr.number,
              event: "REQUEST_CHANGES",
              body: `Automated review: ${message}`
            });
