name: Comment on Product

on: 
  pull_request_target:
    types: [opened]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Create PR Review Comment
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            console.log("Debug: Starting script for PR review comment.");
            const prNumber = context.payload.pull_request.number;
            console.log(`Debug: PR Number is ${prNumber}`);
            const branch = context.payload.pull_request.head.ref;
            console.log(`Debug: Source branch is ${branch}`);
            let message = '';
            if (branch === 'master' || branch === 'beta') {
              message = "Remember to merge commits (DO NOT SQUASH)";
            } else if (branch.startsWith('issues/') || branch.startsWith('feature/')) {
              message = "Remember to squash commits";
            } else {
              message = "Please be mindful that you select the correct merging option";
            }
            console.log(`Debug: Review comment message is "${message}"`);
            // Using the head commit sha; change the file path, line number and diff hunk as needed.
            const commitId = context.payload.pull_request.head.sha;
            const diffHunk = "@@ -0,0 +1 @@\n+Placeholder diff hunk";
            github.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber,
              event: "COMMENT",
              commit_id: commitId,
              body: "Automated review comment",
              comments: [
                {
                  path: "README.md", 
                  line: 1,          
                  side: "RIGHT",
                  diff_hunk: diffHunk,
                  body: message
                }
              ]
            })
            .then(response => console.log("Debug: Review comment created successfully.", response))
            .catch(error => console.error("Debug: Failed to create review comment", error));
