name: Auto Review on PR

on:
  pull_request:
    types: [opened]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Request changes on PR
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = context.payload.pull_request.number;
            const repo = context.repo;
            await github.rest.pulls.createReview({
              owner: repo.owner,
              repo: repo.repo,
              pull_number: prNumber,
              event: "REQUEST_CHANGES",
              body: "Automated review: Please review the changes before merging. 🚨"
            });
