name: Comment on Product


on: 
    pull_request:
        types: [opened]

jobs:
  comment: 
    runs-on: ubuntu-latest
    steps:
      - name: Comment on PR
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = context.payload.pull_request.number;
            const headRef = context.payload.pull_request.head.ref;
            let bodyMessage;

            github.issues.createComment({
              issue_number: prNumber,
              owner: context.repo.owner,
              repo: repo,
              body: 'Hello! Thanks for opening this pull request.'
            })

